In [1]:
!pip install conllu

Collecting conllu
  Downloading conllu-4.5.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: conllu
Successfully installed conllu-4.5.2

In [36]:
import pandas as pd

In [3]:
train_file = '../data/en_ewt-up-train.conllu'
test_file = '../data/en_ewt-up-test.conllu'

In [89]:
with open(train_file, 'r', encoding='utf-8') as f:
    train_data = f.read()

In [91]:
data = []
for doc in train_data.split('\n\n'):
    doc = doc.split('\n')
    sentences = ''
    for line in doc:
        if line and line[0] != '#':
            sentences += line + '\n'
    data.append(sentences)

In [107]:
train_df = pd.DataFrame([x.split('\t') for sent in data for x in sent.split('\n') if x])

In [114]:
train_df.shape

(204609, 46)

In [113]:
train_df[train_df[45].isnull()]

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
0,1,Al,Al,PROPN,NNP,Number=Sing,0,root,0:root,SpaceAfter=No,...,None,None,None,None,None,None,None,None,None,None
1,2,-,-,PUNCT,HYPH,_,1,punct,1:punct,SpaceAfter=No,...,None,None,None,None,None,None,None,None,None,None
2,3,Zaman,Zaman,PROPN,NNP,Number=Sing,1,flat,1:flat,_,...,None,None,None,None,None,None,None,None,None,None
3,4,:,:,PUNCT,:,_,1,punct,1:punct,_,...,None,None,None,None,None,None,None,None,None,None
4,5,American,american,ADJ,JJ,Degree=Pos,6,amod,6:amod,_,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204604,22,on,on,ADP,IN,_,24,case,24:case,_,...,None,None,None,None,None,None,None,None,None,None
204605,23,my,my,PRON,PRP$,Number=Sing|Person=1|Poss=Yes|PronType=Prs,24,nmod:poss,24:nmod:poss,_,...,None,None,None,None,None,None,None,None,None,None
204606,24,car,car,NOUN,NN,Number=Sing,21,obl,21:obl:on,SpaceAfter=No,...,None,None,None,None,None,None,None,None,None,None
204607,25,),),PUNCT,-RRB-,_,4,punct,4:punct,SpaceAfter=No,...,None,None,None,None,None,None,None,None,None,None
204608,26,.,.,PUNCT,.,_,4,punct,4:punct,_,...,None,None,None,None,None,None,None,None,None,None

In [54]:
train_data[train_data[21] !+ None]

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,1,Al,Al,PROPN,NNP,Number=Sing,0,root,0:root,SpaceAfter=No,...,None,None,None,None,None,None,None,None,None,None
1,2,-,-,PUNCT,HYPH,_,1,punct,1:punct,SpaceAfter=No,...,None,None,None,None,None,None,None,None,None,None
2,3,Zaman,Zaman,PROPN,NNP,Number=Sing,1,flat,1:flat,_,...,None,None,None,None,None,None,None,None,None,None
3,4,:,:,PUNCT,:,_,1,punct,1:punct,_,...,None,None,None,None,None,None,None,None,None,None
4,5,American,american,ADJ,JJ,Degree=Pos,6,amod,6:amod,_,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,18,in,in,ADP,IN,_,19,case,19:case,_,...,_,_,_,None,None,None,None,None,None,None
220,19,Vietnam,Vietnam,PROPN,NNP,Number=Sing,13,obl,13:obl:in,SpaceAfter=No,...,_,ARGM-LOC,_,None,None,None,None,None,None,None
221,20,.,.,PUNCT,.,_,2,punct,2:punct,_,...,_,_,_,None,None,None,None,None,None,None
222,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
223,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [46]:
train_data[not train_data['21'].isna()]

KeyError: '21'

In [8]:
train_parsed = parse(train_data)

In [21]:
train_parsed[0][6]

{'id': 7,
 'form': 'killed',
 'lemma': 'kill',
 'upos': 'VERB',
 'xpos': 'VBD',
 'feats': {'Mood': 'Ind', 'Tense': 'Past', 'VerbForm': 'Fin'},
 'head': 1,
 'deprel': 'parataxis',
 'deps': [('parataxis', 1)],
 'misc': None}